base: baseline_syncdist.yaml

method: diffusemix
diffusemix_manifest: ./data/diffusemix/imagenet100/paper_1x_256_seed0
diffusemix_train_mode: append

run_name: imagenet100_preact_resnet18_diffusemix_paper_1x_256_syncdist_e400
