dataset: svhn_cropped
data_dir: ./data
model: preact_resnet18
method: fmix

batch_size: 128
epochs: 200
validation_split: 0.1
val_source: test
eval_on_test_each_epoch: false
final_test: true

learning_rate: 0.1
momentum: 0.9
weight_decay: 0.0005
lr_schedule: cosine

fmix_alpha: 1.0
fmix_decay: 3.0
fmix_prob: 1.0
fmix_per_sample: true
basic_aug: false
seed: 0
save_csv: true
run_name: svhn_cropped_preact_resnet18_fmix
save_checkpoint: true
save_best_only: true
log_time: true
distributed: true
